In [9]:
#Necessary imports that you'd need

In [10]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_recall_fscore_support
from sklearn.metrics import f1_score, precision_score, recall_score, confusion_matrix, classification_report

from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import BernoulliNB

#### Use a label Encoder for converting Categorical Strings into 0/1 for easier data handling. See documentation here : https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html

In [11]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

#### Load your data file (.csv) below **

In [12]:
df = pd.read_csv('./data/house-votes-84.csv')

#### check the dimensions of your dataframe **

In [13]:
df.shape

(435, 17)

#### Checking for missing values below **

In [14]:
df.isna().sum()

Class Name                                  0
handicapped-infants                        12
water-project-cost-sharing                 48
adoption-of-the-budget-resolution          11
physician-fee-freeze                       11
el-salvador-aid                            15
religious-groups-in-schools                11
anti-satellite-test-ban                    14
aid-to-nicaraguan-contras                  15
mx-missile                                 22
immigration                                 7
synfuels-corporation-cutback               21
education-spending                         31
superfund-right-to-sue                     25
crime                                      17
duty-free-exports                          28
export-administration-act-south-africa    104
dtype: int64

### Treatment 1 : Dropping Missing Values below **

In [15]:
df_dropNA = df.dropna(inplace=False)
#why are we doing an inplace false?

#### check the dimensions of your dataframe again **

In [16]:
df_dropNA.shape

(232, 17)

#### transforming your dataframe using label encoding - converting n/y to 0/1 **
hint: use .apply on your dataframe and function as le.fit_transform


In [17]:
#label encoding - converting n/y to 0/1
df_transformed = df_dropNA.apply(le.fit_transform)

#### separating predictors and target columns **

In [18]:
#separating columns for train test split
X = df_transformed.drop(columns=['Class Name'])
y = df_transformed[['Class Name']]

#### do a train test split. 
use https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html 

keep test_size=0.3 and set random state to 1 as your parameters

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

#### Classifier 1 - Run NaiveBayes Classifier
There are different sub-classifiers that we can use. Choose the appropriate one looking at the socumentation : https://scikit-learn.org/stable/modules/naive_bayes.html

Train your classifier on training set only, use X_train, y_train

In [20]:
#initialize your classifier
print("Naive-Bayes Classifier")
nb = BernoulliNB()

#fit your classifier to training set
nb = nb.fit(X_train, y_train)

Naive-Bayes Classifier


c:\users\balav\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


#### evaluate your classifier **

refer https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html for precision 


In [21]:
#use your classifier to predict on the test Set : X_test, save it to a temporary variable y_pred
y_pred = nb.predict(X_test)

In [22]:
#compare y_pred with actual targets for your test set(y_test) and calculate precision, recall, f1-score
print("Precision: %0.2f" %precision_score(y_test, y_pred , average="macro"))
print("Recall:  %0.2f" %recall_score(y_test, y_pred , average="macro"))
print("F1-score:  %0.2f" %f1_score(y_test, y_pred , average="macro"))
#compute recall and f1-score

Precision: 0.93
Recall:  0.91
F1-score:  0.91


In [23]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[37  0]
 [ 6 27]]
              precision    recall  f1-score   support

           0       0.86      1.00      0.92        37
           1       1.00      0.82      0.90        33

    accuracy                           0.91        70
   macro avg       0.93      0.91      0.91        70
weighted avg       0.93      0.91      0.91        70



#### Classifier 2 - Run Decision Trees
Documentation: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

Train your classifier on training set only, use X_train, y_train

In [24]:
print("Decision Tree Classifier")
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

Decision Tree Classifier


#### evaluate your classifier **


In [25]:
#y-pred - same as above
y_pred = clf.predict(X_test)

#compare y_pred with actual targets for your test set(y_test) and calculate precision, recall, f1-score
print("Precision: %0.2f" %precision_score(y_test, y_pred , average="macro"))
print("Recall:  %0.2f" %recall_score(y_test, y_pred , average="macro"))
print("F1-score:  %0.2f" %f1_score(y_test, y_pred , average="macro"))

Precision: 0.97
Recall:  0.97
F1-score:  0.97


In [26]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[37  0]
 [ 2 31]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.97        37
           1       1.00      0.94      0.97        33

    accuracy                           0.97        70
   macro avg       0.97      0.97      0.97        70
weighted avg       0.97      0.97      0.97        70



### Treatment 2 : Treating missing values as a 3rd category**

In [27]:
#filling NA with 'x' - a temporaty variable 
#hint: use fillna

df_fillNewCat = df.fillna('x',inplace=False)

#### check the dimensions of your dataframe again **

In [28]:
#in this case the dimension of your dataframe should be same as the original one - when your loaded the data 1st
df_fillNewCat.shape

(435, 17)

#### transforming your dataframe using label encoding - converting n/y to 0/1 **
hint: use .apply on your dataframe and function as le.fit_transform


In [29]:
df_transformed = df_fillNewCat.apply(le.fit_transform)

#### separating predictors and target columns **

In [30]:
X = df_transformed.drop(columns=['Class Name'])
y = df_transformed[['Class Name']]

#### do a train test split. 
use https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html 

keep test_size=0.3 and set random state to 1 as your parameters

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

#### Classifier 1 - Run NaiveBayes Classifier
There are different sub-classifiers that we can use. Choose the appropriate one looking at the socumentation : https://scikit-learn.org/stable/modules/naive_bayes.html

Train your classifier on training set only, use X_train, y_train

In [32]:
#initialize your classifier
print("Naive-Bayes Classifier")
nb = BernoulliNB()

#fit your classifier to training set
nb = nb.fit(X_train, y_train)

Naive-Bayes Classifier


c:\users\balav\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


#### evaluate your classifier **

refer https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html for precision 


In [33]:
#use your classifier to predict on the test Set : X_test, save it to a temporary variable y_pred
y_pred = nb.predict(X_test)

In [34]:
#compare y_pred with actual targets for your test set(y_test) and calculate precision, recall, f1-score
print("Precision: %0.2f" %precision_score(y_test, y_pred , average="macro"))
print("Recall:  %0.2f" %recall_score(y_test, y_pred , average="macro"))
print("F1-score:  %0.2f" %f1_score(y_test, y_pred , average="macro"))
#compute recall and f1-score

Precision: 0.88
Recall:  0.91
F1-score:  0.89


In [50]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[78 11]
 [ 2 40]]
             precision    recall  f1-score   support

          0       0.97      0.88      0.92        89
          1       0.78      0.95      0.86        42

avg / total       0.91      0.90      0.90       131



#### Classifier 2 - Run Decision Trees
Documentation: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

Train your classifier on training set only, use X_train, y_train

In [27]:
print("Decision Tree Classifier")
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

Decision Tree Classifier


#### evaluate your classifier **


In [28]:
#y-pred - same as above
y_pred = clf.predict(X_test)

#compare y_pred with actual targets for your test set(y_test) and calculate precision, recall, f1-score
print("Precision: %0.2f" %precision_score(y_test, y_pred , average="macro"))
print("Recall:  %0.2f" %recall_score(y_test, y_pred , average="macro"))
print("F1-score:  %0.2f" %f1_score(y_test, y_pred , average="macro"))

Precision: 0.93
Recall:  0.93
F1-score:  0.93


In [29]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85  4]
 [ 4 38]]
             precision    recall  f1-score   support

          0       0.96      0.96      0.96        89
          1       0.90      0.90      0.90        42

avg / total       0.94      0.94      0.94       131



### Treatment 3 : Replacing missing values with Most Common values**

In [30]:
#this is an example of how you can do this - implement it on all the columns that have a missing value
#df['crime'] = df['crime'].astype('category')
#df['crime'].fillna(df['crime'].mode()[0],inplace=True)

df_fillMostFr = pd.DataFrame()
for col in df.columns:
    df_fillMostFr[col] = df[col].astype('category')
    df_fillMostFr[col].fillna(df[col].mode()[0],inplace=True)

#### Repeat the same things that you did before

1.Check dimensions
2. Transform your data
3. Separate Target and predictors
4. Do a train test split
5. Run and evaluate NaiveBayes and DecisionTree classifiers

In [31]:
#1
df_fillMostFr.shape

(435, 17)

In [32]:
#2
df_transformed = df_fillMostFr.apply(le.fit_transform)

In [33]:
#3
X = df_transformed.drop(columns=['Class Name'])
y = df_transformed[['Class Name']]

In [34]:
#4
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [127]:
#5

#### Classifier 1 - Run NaiveBayes Classifier
There are different sub-classifiers that we can use. Choose the appropriate one looking at the socumentation : https://scikit-learn.org/stable/modules/naive_bayes.html

Train your classifier on training set only, use X_train, y_train

In [35]:
#initialize your classifier
print("Naive-Bayes Classifier")
nb = BernoulliNB()

#fit your classifier to training set
nb = nb.fit(X_train, y_train)

Naive-Bayes Classifier


/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


#### evaluate your classifier **

refer https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html for precision 


In [36]:
#use your classifier to predict on the test Set : X_test, save it to a temporary variable y_pred
y_pred = nb.predict(X_test)

In [37]:
#compare y_pred with actual targets for your test set(y_test) and calculate precision, recall, f1-score
print("Precision: %0.2f" %precision_score(y_test, y_pred , average="macro"))
print("Recall:  %0.2f" %recall_score(y_test, y_pred , average="macro"))
print("F1-score:  %0.2f" %f1_score(y_test, y_pred , average="macro"))
#compute recall and f1-score

Precision: 0.88
Recall:  0.91
F1-score:  0.89


In [38]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[79 10]
 [ 3 39]]
             precision    recall  f1-score   support

          0       0.96      0.89      0.92        89
          1       0.80      0.93      0.86        42

avg / total       0.91      0.90      0.90       131



#### Classifier 2 - Run Decision Trees
Documentation: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

Train your classifier on training set only, use X_train, y_train

In [39]:
print("Decision Tree Classifier")
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

Decision Tree Classifier


#### evaluate your classifier **


In [40]:
#y-pred - same as above
y_pred = clf.predict(X_test)

#compare y_pred with actual targets for your test set(y_test) and calculate precision, recall, f1-score
print("Precision: %0.2f" %precision_score(y_test, y_pred , average="macro"))
print("Recall:  %0.2f" %recall_score(y_test, y_pred , average="macro"))
print("F1-score:  %0.2f" %f1_score(y_test, y_pred , average="macro"))

Precision: 0.95
Recall:  0.93
F1-score:  0.94


In [51]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[78 11]
 [ 2 40]]
             precision    recall  f1-score   support

          0       0.97      0.88      0.92        89
          1       0.78      0.95      0.86        42

avg / total       0.91      0.90      0.90       131



### CrossValidation
A great read on this : https://towardsdatascience.com/cross-validation-70289113a072

#### Let's start with Treatment 1: Dropping missing values
#### Repeat these same things that you did before

1. Check dimensions
2. Transform your data
3. Separate Target and predictors


In [52]:
#1
df.shape

(435, 17)

In [53]:
df.isna().sum()

Class Name                                  0
handicapped-infants                        12
water-project-cost-sharing                 48
adoption-of-the-budget-resolution          11
physician-fee-freeze                       11
el-salvador-aid                            15
religious-groups-in-schools                11
anti-satellite-test-ban                    14
aid-to-nicaraguan-contras                  15
mx-missile                                 22
immigration                                 7
synfuels-corporation-cutback               21
education-spending                         31
superfund-right-to-sue                     25
crime                                      17
duty-free-exports                          28
export-administration-act-south-africa    104
dtype: int64

In [54]:
#Dropping NAs
df_dropNA = df.dropna(inplace=False)

In [55]:
#label encoding - converting n/y to 0/1
df_transformed = df_dropNA.apply(le.fit_transform)

In [56]:
#separating columns for train test split
#X = df_transformed.drop(columns=['Class Name'])
#y = df_transformed[['Class Name']]

#### Does the above statement throw an exception? Can you guess why? 
Check if the datatypes of X and y and see if they match that of cross_val_score signature.

Hint: use type() function

#### How do you change these dataframes to datatypes that'll fit your function signature?

Hint: use .values and convert them to numpy array format.


#### do a train test split. 
use https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html 

keep test_size=0.3 and set random state to 1 as your parameters

In [57]:
#3 converting to numpy array
X = np.array(df_transformed.drop(columns=['Class Name']).values)
y = np.array(df_transformed['Class Name'].values)

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

Now instead of using train-test split, we'll cross-validate on the whole of X and y to maximize the scores

Let's start with NaiveBayes

In [59]:
print("Naive-Bayes Classifier")
nb = BernoulliNB()
#scores = cross_val_score(nb, X, y, cv=5, scoring=scoring)
print("Precision: %0.2f (+/- %0.2f)" % (cross_val_score(nb, X, y, cv=5, scoring='precision').mean(), cross_val_score(nb, X, y, cv=5, scoring='precision').std() * 2))
print("Recall: %0.2f (+/- %0.2f)" % (cross_val_score(nb, X, y, cv=5, scoring='recall').mean(), cross_val_score(nb, X, y, cv=5, scoring='recall').std() * 2))
print("F1-score: %0.2f (+/- %0.2f)" % (cross_val_score(nb, X, y, cv=5, scoring='f1').mean(), cross_val_score(nb, X, y, cv=5, scoring='f1').std() * 2))

Naive-Bayes Classifier
Precision: 0.89 (+/- 0.19)
Recall: 0.95 (+/- 0.09)
F1-score: 0.91 (+/- 0.13)


In [60]:
#Repeat the same steps for DecisionTree Classifier
print("Decision Tree Classifier")
clf = tree.DecisionTreeClassifier()
print("Precision: %0.2f (+/- %0.2f)" % (cross_val_score(clf, X, y, cv=5, scoring='precision').mean(), cross_val_score(clf, X, y, cv=5, scoring='precision').std() * 2))
print("Recall: %0.2f (+/- %0.2f)" % (cross_val_score(clf, X, y, cv=5, scoring='recall').mean(), cross_val_score(clf, X, y, cv=5, scoring='recall').std() * 2))
print("F1-score: %0.2f (+/- %0.2f)" % (cross_val_score(clf, X, y, cv=5, scoring='f1').mean(), cross_val_score(clf, X, y, cv=5, scoring='f1').std() * 2))

Decision Tree Classifier
Precision: 0.96 (+/- 0.11)
Recall: 0.95 (+/- 0.09)
F1-score: 0.95 (+/- 0.07)


#### Repeat for Treatment 2 and 3 and record scores for each classifier

In [75]:
#Treatment 2

In [61]:
#filling NA with m
df_fillNewCat = df.fillna('m',inplace=False)

In [62]:
df_transformed = df_fillNewCat.apply(le.fit_transform)

In [63]:
#3 converting to numpy array
X = np.array(df_transformed.drop(columns=['Class Name']).values)
y = np.array(df_transformed['Class Name'].values)

In [79]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [64]:
print("Naive-Bayes Classifier")
nb = BernoulliNB()
#scores = cross_val_score(nb, X, y, cv=5, scoring=scoring)
print("Precision: %0.2f (+/- %0.2f)" % (cross_val_score(nb, X, y, cv=5, scoring='precision').mean(), cross_val_score(nb, X, y, cv=5, scoring='precision').std() * 2))
print("Recall: %0.2f (+/- %0.2f)" % (cross_val_score(nb, X, y, cv=5, scoring='recall').mean(), cross_val_score(nb, X, y, cv=5, scoring='recall').std() * 2))
print("F1-score: %0.2f (+/- %0.2f)" % (cross_val_score(nb, X, y, cv=5, scoring='f1').mean(), cross_val_score(nb, X, y, cv=5, scoring='f1').std() * 2))

Naive-Bayes Classifier
Precision: 0.64 (+/- 0.38)
Recall: 0.09 (+/- 0.15)
F1-score: 0.15 (+/- 0.19)


In [65]:
#Repeat the same steps for DecisionTree Classifier
print("Decision Tree Classifier")
clf = tree.DecisionTreeClassifier()
print("Precision: %0.2f (+/- %0.2f)" % (cross_val_score(clf, X, y, cv=5, scoring='precision').mean(), cross_val_score(clf, X, y, cv=5, scoring='precision').std() * 2))
print("Recall: %0.2f (+/- %0.2f)" % (cross_val_score(clf, X, y, cv=5, scoring='recall').mean(), cross_val_score(clf, X, y, cv=5, scoring='recall').std() * 2))
print("F1-score: %0.2f (+/- %0.2f)" % (cross_val_score(clf, X, y, cv=5, scoring='f1').mean(), cross_val_score(clf, X, y, cv=5, scoring='f1').std() * 2))

Decision Tree Classifier
Precision: 0.93 (+/- 0.10)
Recall: 0.93 (+/- 0.10)
F1-score: 0.93 (+/- 0.05)


In [82]:
#treatment 3

In [66]:
df.shape

(435, 17)

In [67]:
df.isna().sum()

Class Name                                  0
handicapped-infants                        12
water-project-cost-sharing                 48
adoption-of-the-budget-resolution          11
physician-fee-freeze                       11
el-salvador-aid                            15
religious-groups-in-schools                11
anti-satellite-test-ban                    14
aid-to-nicaraguan-contras                  15
mx-missile                                 22
immigration                                 7
synfuels-corporation-cutback               21
education-spending                         31
superfund-right-to-sue                     25
crime                                      17
duty-free-exports                          28
export-administration-act-south-africa    104
dtype: int64

In [68]:
#replacing NAs with most frequent
df_fillMostFr = pd.DataFrame()
for col in df.columns:
    df_fillMostFr[col] = df[col].astype('category')
    df_fillMostFr[col].fillna(df[col].mode()[0],inplace=True)

In [69]:
df_transformed = df_fillMostFr.apply(le.fit_transform)

In [70]:
X = np.array(df_transformed.drop(columns=['Class Name']).values)
y = np.array(df_transformed['Class Name'].values)

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [72]:
print("Naive-Bayes Classifier")
nb = BernoulliNB()
#scores = cross_val_score(nb, X, y, cv=5, scoring=scoring)
print("Precision: %0.2f (+/- %0.2f)" % (cross_val_score(nb, X, y, cv=5, scoring='precision').mean(), cross_val_score(nb, X, y, cv=5, scoring='precision').std() * 2))
print("Recall: %0.2f (+/- %0.2f)" % (cross_val_score(nb, X, y, cv=5, scoring='recall').mean(), cross_val_score(nb, X, y, cv=5, scoring='recall').std() * 2))
print("F1-score: %0.2f (+/- %0.2f)" % (cross_val_score(nb, X, y, cv=5, scoring='f1').mean(), cross_val_score(nb, X, y, cv=5, scoring='f1').std() * 2))

Naive-Bayes Classifier
Precision: 0.85 (+/- 0.18)
Recall: 0.92 (+/- 0.06)
F1-score: 0.88 (+/- 0.11)


In [73]:
#Repeat the same steps for DecisionTree Classifier
print("Decision Tree Classifier")
clf = tree.DecisionTreeClassifier()
print("Precision: %0.2f (+/- %0.2f)" % (cross_val_score(clf, X, y, cv=5, scoring='precision').mean(), cross_val_score(clf, X, y, cv=5, scoring='precision').std() * 2))
print("Recall: %0.2f (+/- %0.2f)" % (cross_val_score(clf, X, y, cv=5, scoring='recall').mean(), cross_val_score(clf, X, y, cv=5, scoring='recall').std() * 2))
print("F1-score: %0.2f (+/- %0.2f)" % (cross_val_score(clf, X, y, cv=5, scoring='f1').mean(), cross_val_score(clf, X, y, cv=5, scoring='f1').std() * 2))

Decision Tree Classifier
Precision: 0.91 (+/- 0.07)
Recall: 0.93 (+/- 0.09)
F1-score: 0.93 (+/- 0.02)
